/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'samarthg' at '31/1/16 4:54 PM' with Gradle 2.2
 *
 * @author samarthg, @date 31/1/16 4:54 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
	 public static void main(String[] args) {
        // Prints "Hello, World" to the terminal window.
        System.out.println("Hello, World");
    }

}
